version: '2'
services:
  db:
    build: ./docker/database/
    user: rowboat
    volumes:
      - ./.data:/var/lib/postgresql/data
  redis:
    build: ./docker/redis
    user: rowboat
    command: redis-server --appendonly yes
    volumes:
      - ./.data:/data
    ports:
      - "127.0.0.1:6379:6379"
  web:
    build: .
    user: rowboat
    command: pypy manage.py serve -r
    volumes:
      - .rowboat_home:/home/rowboat
      - .:/opt/rowboat
    ports:
      - "127.0.0.1:8686:8686"
    depends_on:
      - db
      - redis
  frontend:
    build: ./frontend/
    user: rowboat
    environment:
      - NODE_ENV=docker
    command: npm run serve
    volumes:
      - ./frontend:/opt/frontend
    ports:
      - "127.0.0.1:24458:8080"
    depends_on:
      - web
  bot:
    build: .
    user: rowboat
    command: pypy manage.py bot -e docker
    volumes:
      - .rowboat_home:/home/rowboat
      - .:/opt/rowboat
    ports:
      - "127.0.0.1:7171:7171"
    depends_on:
      - web
