version: '2'
services:
  db:
    build: ./docker/database/
    user: rowboat
    volumes:
      - ./.data:/var/lib/postgresql/data
  redis:
    build: ./docker/redis
    user: rowboat
    command: redis-server --appendonly yes
    volumes:
      - ./.data:/data
    ports:
      - "127.0.0.1:6379:6379"
  statsd:
    build: .
    user: rowboat
    volumes:
      - .:/opt/rowboat
    command: python /opt/rowboat/docker/nulld.py
    ports:
      - "127.0.0.1:8125:8125"
    stop_signal: SIGKILL
  web:
    build: .
    user: rowboat
    command: python manage.py serve -r
    volumes:
      - .:/opt/rowboat
    ports:
      - "127.0.0.1:8686:8686"
    depends_on:
      - db
      - redis
      - statsd
  frontend:
    build: ./frontend/
    user: rowboat
    environment:
      - NODE_ENV=docker
    command: npm run serve
    volumes:
      - ./frontend:/opt/frontend
    ports:
      - "127.0.0.1:24458:8080"
    depends_on:
      - web
  bot:
    build: .
    user: rowboat
    command: python manage.py bot -e docker
    volumes:
      - .:/opt/rowboat
    ports:
      - "127.0.0.1:7171:7171"
    depends_on:
      - web
  #workers:
  #  build: .
  #  command: python manage.py workers
  #  volumes:
  #    - .:/opt/rowboat
  #  depends_on:
  #    - web
